# CONTROL-INFORMED CANDIDATE configuration, not a compliance attestation.
# Covers only technical settings expressible as AVM module inputs. Does NOT
# establish FedRAMP / CCC / NIST compliance. Mapped controls may be only
# partially satisfied; unmapped and process/evidence controls are out of scope.
# Human review and deployment-context validation are required before use.
#
# Generated by avm-config-generator v0.1.0 at 2026-06-10T13:43:21Z
# AVM module:   Azure/avm-res-storage-storageaccount/azurerm
# Module ver:   0.7.2  (provider azapi ~> 2.8)
# Verified:     True
# Sources:      {"ccc": ["CCC.ObjStor", "CCC.Core (imported)"], "ccc_catalog_ref": "https://github.com/finos/common-cloud-controls/blob/main/catalogs/storage/object/controls.yaml", "ccc_retrieved": "2026-06-09", "fedramp": []}

variable "location" {
  description = "Azure region where the storage account should be deployed."
  type        = string
}

variable "name" {
  description = "Storage account name (3-24 lowercase alphanumeric characters)."
  type        = string

  validation {
    condition     = can(regex("^[a-z0-9]{3,24}$", var.name))
    error_message = "The name must be between 3 and 24 characters; valid characters are lowercase letters and numbers."
  }
}

variable "parent_id" {
  description = "Resource group ID in the form /subscriptions/{id}/resourceGroups/{name}."
  type        = string
}

variable "allow_nested_items_to_be_public" {
  description = <<-EOT
    Controls: CCC.ObjStor.CN02 [coverage: partial]
    Allow nested items within the account to opt into being public.
    Limitation: 'Uniform bucket-level access' is a GCP concept; this is the closest Azure equivalent (no anonymous public access), not a 1:1.
  EOT
  type        = bool
  default     = false
}

variable "shared_access_key_enabled" {
  description = <<-EOT
    Controls: CCC.ObjStor.CN02 [coverage: partial]
    Permit Shared Key authorization on the storage account.
    Limitation: Any tooling/workload still using account keys or key-derived SAS will break — confirm Entra-based access paths first.
    Limitation: Does not itself assign RBAC roles (use var.role_assignments on the AVM module).
  EOT
  type        = bool
  default     = false
}

variable "default_to_oauth_authentication" {
  description = <<-EOT
    Controls: CCC.ObjStor.CN02 [coverage: partial]
    Default to Entra ID authorization in the Azure portal.
    Limitation: Any tooling/workload still using account keys or key-derived SAS will break — confirm Entra-based access paths first.
    Limitation: Does not itself assign RBAC roles (use var.role_assignments on the AVM module).
  EOT
  type        = bool
  default     = true
}

variable "blob_properties" {
  description = <<-EOT
    Controls: CCC.ObjStor.CN04, CCC.ObjStor.CN05 [coverage: full, partial]
    Blob service-level settings for the storage account.
    Limitation: 30 days is illustrative — set per the data class / regulatory retention requirement (module allows 1–365).
    Limitation: Soft delete aids recovery but does NOT make retention irrevocable (see CCC.ObjStor.CN03, requires_context).
  EOT
  type = object({
    automatic_snapshot_policy_enabled = optional(bool)
    change_feed = optional(object({
      enabled           = optional(bool)
      retention_in_days = optional(number)
    }))
    container_delete_retention_policy = optional(object({
      allow_permanent_delete = optional(bool)
      days                   = optional(number)
      enabled                = optional(bool)
    }))
    cors_rules = optional(list(object({
      allowed_headers    = list(string)
      allowed_methods    = list(string)
      allowed_origins    = list(string)
      exposed_headers    = list(string)
      max_age_in_seconds = number
    })))
    default_service_version = optional(string)
    delete_retention_policy = optional(object({
      allow_permanent_delete = optional(bool)
      days                   = optional(number)
      enabled                = optional(bool)
    }))
    last_access_time_tracking_policy = optional(object({
      blob_type                    = optional(list(string))
      enable                       = bool
      name                         = optional(string)
      tracking_granularity_in_days = optional(number)
    }))
    restore_policy = optional(object({
      days    = optional(number)
      enabled = bool
    }))
    versioning_enabled = optional(bool)
  })
  default = {
    versioning_enabled = true
    change_feed = {
      enabled           = true
      retention_in_days = 1
    }
    restore_policy = {
      enabled = false
      days    = 1
    }
    last_access_time_tracking_policy = {
      enable = false
      name   = "AccessTimeTracking"
    }
    delete_retention_policy = {
      enabled = true
      days    = 30
    }
    container_delete_retention_policy = {
      enabled = true
      days    = 30
    }
  }
}

variable "infrastructure_encryption_enabled" {
  description = <<-EOT
    Controls: CCC.Core.CN02 [coverage: partial]
    Enable infrastructure encryption (forces replacement when toggled).
    Limitation: At-rest encryption is on by default regardless; this strengthens it.
    Limitation: Forces a new resource — cannot be toggled on an existing account (module default is false).
  EOT
  type        = bool
  default     = true
}

variable "network_rules" {
  description = <<-EOT
    Controls: CCC.Core.CN05 [coverage: partial]
    Network ACLs for the storage account.
    Limitation: Allowed IP ranges (ip_rules) / subnet IDs (virtual_network_subnet_ids) are deployment-specific and intentionally left for the operator.
    Limitation: bypass=["AzureServices"] is a pragmatic default; tighten to [] for the strictest posture.
  EOT
  type = object({
    bypass                     = optional(set(string), ["AzureServices"])
    default_action             = optional(string, "Deny")
    ip_rules                   = optional(set(string), [])
    virtual_network_subnet_ids = optional(set(string), [])
    private_link_access = optional(list(object({
      endpoint_resource_id = string
      endpoint_tenant_id   = optional(string)
    })))
    timeouts = optional(object({
      create = optional(string)
      delete = optional(string)
      read   = optional(string)
      update = optional(string)
    }))
  })
  default = {
    default_action = "Deny"
    bypass         = ["AzureServices"]
  }
}

variable "public_network_access_enabled" {
  description = <<-EOT
    Controls: CCC.Core.CN05 [coverage: partial]
    Whether public network access is enabled.
    Limitation: Does NOT create private endpoints, private DNS zones, or VNet integration — configure var.private_endpoints (and DNS) on the AVM module for the account to remain reachable.
  EOT
  type        = bool
  default     = false
}

variable "https_traffic_only_enabled" {
  description = <<-EOT
    Controls: CCC.Core.CN01 [coverage: full]
    Force HTTPS for storage requests.
  EOT
  type        = bool
  default     = true
}

variable "min_tls_version" {
  description = <<-EOT
    Controls: CCC.Core.CN01 [coverage: partial]
    Minimum TLS version (TLS1_0, TLS1_1, TLS1_2).
    Limitation: TLS1_2 is the highest the module/Azure exposes for storage; it is also the module default.
  EOT
  type        = string
  default     = "TLS1_2"
}

variable "private_endpoints" {
  description = <<-EOT
    Controls: CCC.Core.CN05 [coverage: partial]
    Map of private endpoints to create for the storage account (passed through to
    the AVM module). Each entry typically specifies subnet_resource_id,
    subresource_name (e.g. "blob"/"file") and private_dns_zone_resource_ids.
  EOT
  type        = any
  default     = {}
}

variable "extra_containers" {
  description = <<-EOT
    Additional (mutable) blob containers to create alongside the immutable default
    container, via the ARM control plane. Used to provision the Flex function's
    deploymentpackage container on the governed account without enabling data-plane
    (public) access.
  EOT
  type = map(object({
    name = string
  }))
  default = {}
}

variable "managed_identities" {
  description = <<-EOT
    Controls: CCC.ObjStor.CN01, CCC.Core.CN02 [coverage: partial]
    Managed identities assigned to the storage account. A user-assigned identity
    is required for customer-managed-key (CMK) access to Key Vault.
  EOT
  type        = any
  default     = {}
}

variable "customer_managed_key" {
  description = <<-EOT
    Controls: CCC.ObjStor.CN01, CCC.Core.CN02 [coverage: partial]
    Customer-managed key (CMK) configuration: the Key Vault resource ID, key
    name, and the user-assigned identity used to reach the key. Null leaves the
    account on Microsoft-managed keys (still encrypted at rest).
  EOT
  type        = any
  default     = null
}
