# This file is CONTROL-INFORMED CANDIDATE configuration, not a compliance
# attestation. It covers only technical settings expressible as AVM module
# inputs. It does NOT establish FedRAMP / CCC / NIST compliance. Mapped
# controls may be only partially satisfied; unmapped and process/evidence
# controls are out of scope here. Human review and deployment-context
# validation are required before use.
#
# Generated by avm-config-generator v0.1.0 at 2026-06-15T09:47:40Z
# AVM module:   Azure/avm-res-keyvault-vault/azurerm
# Module ver:   0.10.2  (provider azurerm >= 3.117, < 5.0)
# Verified:     True  (false = variable names NOT yet checked against the module)
# Sources:      {"ccc": ["CCC.KeyMgmt", "CCC.Core (imported)"], "ccc_catalog_ref": "https://github.com/finos/common-cloud-controls/blob/main/catalogs/crypto/key/controls.yaml", "ccc_retrieved": "2026-06-09", "fedramp": []}
#
# See key-vault.provenance.json for the authoritative, machine-readable audit trail.

# Controls: CCC.KeyMgmt.CN02  [coverage: partial]
# Limitation: These match the module defaults (all false); emitted to make
# the least-privilege posture explicit. Set the specific one to true only
# when a workload genuinely needs it.
enabled_for_deployment = false

# Controls: CCC.KeyMgmt.CN02  [coverage: partial]
# Limitation: These match the module defaults (all false); emitted to make
# the least-privilege posture explicit. Set the specific one to true only
# when a workload genuinely needs it.
enabled_for_disk_encryption = false

# Controls: CCC.KeyMgmt.CN02  [coverage: partial]
# Limitation: These match the module defaults (all false); emitted to make
# the least-privilege posture explicit. Set the specific one to true only
# when a workload genuinely needs it.
enabled_for_template_deployment = false

# Controls: CCC.KeyMgmt.CN02  [coverage: partial]
# Limitation: RBAC is the module default; this makes it explicit. The actual
# scoping of Decrypt to authorised principals is done via
# var.role_assignments (deployment-specific).
# Limitation: Does not itself assign or restrict any role.
legacy_access_policies_enabled = false

# Controls: CCC.KeyMgmt.CN01  [coverage: supporting]
# Limitation: Preventive control for TH01; it does NOT satisfy CN01's actual
# requirement (near-real-time ALERT on key-version disable/delete) - that is
# covered separately and remains proposed.
# Limitation: Once enabled, purge protection cannot be disabled (module
# default is already true).
purge_protection_enabled = true

# Controls: CCC.KeyMgmt.CN01  [coverage: supporting]
# Limitation: Recovery window only; does not satisfy CN01's alerting
# requirement. Module allows 7-90 days.
soft_delete_retention_days = 90

# Controls: CCC.KeyMgmt.CN04  [coverage: partial]
# Limitation: SKU enables HSM-backed keys but does NOT itself enforce
# approved algorithms or attestation on import - that is an approval workflow
# (see kv.encryption.import-validation).
sku_name = "premium"

# Controls: CCC.Core.CN05  [coverage: partial]
# Limitation: Allowed IP ranges (network_acls.ip_rules) / subnet IDs
# (network_acls.virtual_network_subnet_ids) are deployment-specific and
# intentionally left to the operator.
# Limitation: bypass=AzureServices is pragmatic; tighten to None for the
# strictest posture. network_acls.bypass is a string (AzureServices|None),
# not a list.
network_acls = {
  default_action = "Deny"
  bypass         = "AzureServices"
}

# Controls: CCC.Core.CN05  [coverage: partial]
# Limitation: Does NOT create private endpoints/DNS - configure
# var.private_endpoints for the vault to remain reachable.
public_network_access_enabled = false
