# This file is CONTROL-INFORMED CANDIDATE configuration, not a compliance
# attestation. It covers only technical settings expressible as AVM module
# inputs. It does NOT establish FedRAMP / CCC / NIST compliance. Mapped
# controls may be only partially satisfied; unmapped and process/evidence
# controls are out of scope here. Human review and deployment-context
# validation are required before use.
#
# Generated by avm-config-generator v0.1.0 at 2026-06-15T10:13:13Z
# AVM module:   Azure/avm-res-operationalinsights-workspace/azurerm
# Module ver:   0.5.1  (provider azapi ~> 2.4)
# Verified:     True  (false = variable names NOT yet checked against the module)
# Sources:      {"ccc": ["CCC.Core (imported)"], "fedramp": []}
#
# See log-analytics-workspace.provenance.json for the authoritative, machine-readable audit trail.

# Controls: CCC.Core.CN04, CCC.Core.CN09  [coverage: partial]
# Limitation: Retention period is regulatory/policy-specific — adjust to the
# workload's obligation. v0.5.1 supports 30–730 days (7 only on the Free
# tier).
# Limitation: Retention alone is not immutability; CN09 tamper-resistance
# still needs workspace RBAC and (for the strongest posture) a dedicated
# cluster / immutable export.
log_analytics_workspace_retention_in_days = 365

# Controls: CCC.Core.CN05  [coverage: partial]
# Limitation: Both variables are strings on v0.5.1 ("true" | "false" |
# "SecuredByPerimeter"), not booleans.
# Limitation: Disabling internet access only delivers reachability when
# private connectivity (AMPLS) is wired up — see the
# la.logging.external-log-destination limitation.
log_analytics_workspace_internet_ingestion_enabled = "false"

# Controls: CCC.Core.CN05  [coverage: partial]
# Limitation: Both variables are strings on v0.5.1 ("true" | "false" |
# "SecuredByPerimeter"), not booleans.
# Limitation: Disabling internet access only delivers reachability when
# private connectivity (AMPLS) is wired up — see the
# la.logging.external-log-destination limitation.
log_analytics_workspace_internet_query_enabled = "false"
