# This file is CONTROL-INFORMED CANDIDATE configuration, not a compliance
# attestation. It covers only technical settings expressible as AVM module
# inputs. It does NOT establish FedRAMP / CCC / NIST compliance. Mapped
# controls may be only partially satisfied; unmapped and process/evidence
# controls are out of scope here. Human review and deployment-context
# validation are required before use.
#
# Generated by avm-config-generator v0.1.0 at 2026-06-15T10:13:13Z
# AVM module:   Azure/avm-res-web-site/azurerm
# Module ver:   0.22.0  (provider azapi ~> 2.9)
# Verified:     True  (false = variable names NOT yet checked against the module)
# Sources:      {"ccc": ["CCC.SvlsComp", "CCC.Core (imported)"], "ccc_catalog_ref": "https://github.com/finos/common-cloud-controls/blob/main/catalogs/compute/serverless-computing/controls.yaml", "fedramp": []}
#
# See serverless-function.provenance.json for the authoritative, machine-readable audit trail.

# Controls: CCC.Core.CN05  [coverage: supporting]
# Limitation: Caller cert distribution/validation is an operational concern;
# some PaaS-internal callers may not present a cert.
client_certificate_enabled = true

# Controls: CCC.Core.CN05  [coverage: supporting]
# Limitation: Caller cert distribution/validation is an operational concern;
# some PaaS-internal callers may not present a cert.
client_certificate_mode = "Required"

# Controls: CCC.SvlsComp.CN01, CCC.SvlsComp.CN02  [coverage: supporting]
# Limitation: FC1 requires a matching Flex Consumption service plan
# (service_plan_resource_id) — deployment-specific.
# Limitation: Hosting-plan choice; not itself a complete expression of either
# control.
function_app_uses_fc1 = true

# Controls: CCC.Core.CN03, CCC.Core.CN05  [coverage: supporting]
# Limitation: Managed identity is the auth principal, not MFA; CN03 (MFA for
# human access) is satisfied via Entra Conditional Access, not this module.
managed_identities = {
  system_assigned = true
}

# Controls: CCC.Core.CN05, CCC.SvlsComp.CN01  [coverage: partial]
# Limitation: Disabling public access is necessary but not sufficient for
# CN01 — a private endpoint (see svls.network.private-endpoint) must also be
# wired up.
public_network_access_enabled = false

# Controls: CCC.SvlsComp.CN02  [coverage: partial]
# Limitation: Caps total concurrency, NOT per-entity invocation rate. True
# per-caller throttling (CN02 AR01) must be enforced upstream (APIM
# rate-limit policy or Front Door). 40 is an example ceiling — set per
# workload.
maximum_instance_count = 40

# Controls: CCC.Core.CN01  [coverage: partial]
# Limitation: Module default is already true; pinned here so the baseline is
# explicit and drift is caught.
https_only = true

# Controls: CCC.Core.CN01, CCC.Core.CN05, CCC.Core.CN10  [coverage: partial, supporting]
# Limitation: TLS floor only; does not itself prove cipher suite posture or
# PQC readiness.
# Limitation: Covers the management/deployment endpoint, not the request data
# path.
# Limitation: Disables FTPS entirely; if FTPS deployment is required, use
# 'FtpsOnly' instead.
# Limitation: Requires VNet integration (virtual_network_subnet_id) to take
# effect; egress policy itself lives in the VNet/firewall, not this module.
site_config = {
  minimum_tls_version     = "1.3"
  scm_minimum_tls_version = "1.3"
  ftps_state              = "Disabled"
  vnet_route_all_enabled  = true
}
