# This file is CONTROL-INFORMED CANDIDATE configuration, not a compliance
# attestation. It covers only technical settings expressible as AVM module
# inputs. It does NOT establish FedRAMP / CCC / NIST compliance. Mapped
# controls may be only partially satisfied; unmapped and process/evidence
# controls are out of scope here. Human review and deployment-context
# validation are required before use.
#
# Generated by avm-config-generator v0.1.0 at 2026-06-10T13:43:21Z
# AVM module:   Azure/avm-res-storage-storageaccount/azurerm
# Module ver:   0.7.2  (provider azapi ~> 2.8)
# Verified:     True  (false = variable names NOT yet checked against the module)
# Sources:      {"ccc": ["CCC.ObjStor", "CCC.Core (imported)"], "ccc_catalog_ref": "https://github.com/finos/common-cloud-controls/blob/main/catalogs/storage/object/controls.yaml", "ccc_retrieved": "2026-06-09", "fedramp": []}
#
# See storage-account.provenance.json for the authoritative, machine-readable audit trail.

# Controls: CCC.ObjStor.CN02  [coverage: partial]
# Limitation: 'Uniform bucket-level access' is a GCP concept; this is the
# closest Azure equivalent (no anonymous public access), not a 1:1.
allow_nested_items_to_be_public = false

# Controls: CCC.ObjStor.CN02  [coverage: partial]
# Limitation: Any tooling/workload still using account keys or key-derived
# SAS will break — confirm Entra-based access paths first.
# Limitation: Does not itself assign RBAC roles (use var.role_assignments).
shared_access_key_enabled = false

# Controls: CCC.ObjStor.CN02  [coverage: partial]
# Limitation: Any tooling/workload still using account keys or key-derived
# SAS will break — confirm Entra-based access paths first.
# Limitation: Does not itself assign RBAC roles (use var.role_assignments).
default_to_oauth_authentication = true

# Controls: CCC.ObjStor.CN04, CCC.ObjStor.CN05  [coverage: full, partial]
# Limitation: 30 days is illustrative — set per the data class / regulatory
# retention requirement (module allows 1–365).
# Limitation: Soft delete aids recovery but does NOT make retention
# irrevocable (see CCC.ObjStor.CN03, requires_context below).
# change_feed / restore_policy / last_access_time_tracking_policy are empty
# stubs required by AVM v0.7.2 validation — not compliance settings.
blob_properties = {
  versioning_enabled = true
  change_feed = {
    enabled           = true
    retention_in_days = 1
  }
  restore_policy = {
    enabled = false
    days    = 1
  }
  last_access_time_tracking_policy = {
    enable = false
    name   = "AccessTimeTracking"
  }
  delete_retention_policy = {
    enabled = true
    days    = 30
  }
  container_delete_retention_policy = {
    enabled = true
    days    = 30
  }
}

# Controls: CCC.Core.CN02  [coverage: partial]
# Limitation: At-rest encryption is on by default regardless; this
# strengthens it.
# Limitation: Forces a new resource — cannot be toggled on an existing
# account (module default is false).
infrastructure_encryption_enabled = true

# Controls: CCC.Core.CN05  [coverage: partial]
# Limitation: Allowed IP ranges (network_rules.ip_rules) / subnet IDs
# (network_rules.virtual_network_subnet_ids) are deployment-specific and
# intentionally left for the operator.
# Limitation: bypass=["AzureServices"] is a pragmatic default; tighten to []
# for the strictest posture. (These also match the module defaults.)
network_rules = {
  default_action = "Deny"
  bypass = [
    "AzureServices"
  ]
}

# Controls: CCC.Core.CN05  [coverage: partial]
# Limitation: Does NOT create private endpoints, private DNS zones, or VNet
# integration — configure var.private_endpoints (and DNS) for the account to
# remain reachable.
public_network_access_enabled = false

# Controls: CCC.Core.CN01  [coverage: full]
https_traffic_only_enabled = true

# Controls: CCC.Core.CN01  [coverage: partial]
# Limitation: TLS1_2 is the highest the module/Azure exposes for storage
# (values: TLS1_0, TLS1_1, TLS1_2); it is also the module default.
min_tls_version = "TLS1_2"
