# This file is CONTROL-INFORMED CANDIDATE configuration, not a compliance
# attestation. It covers only technical settings expressible as AVM module
# inputs. It does NOT establish FedRAMP / CCC / NIST compliance. Mapped
# controls may be only partially satisfied; unmapped and process/evidence
# controls are out of scope here. Human review and deployment-context
# validation are required before use.
#
# Generated by avm-config-generator v0.1.0 at 2026-06-15T10:13:13Z
# AVM module:   Azure/avm-res-compute-virtualmachine/azurerm
# Module ver:   0.21.0  (provider azapi+azurerm >= 1.10, < 2.0)
# Verified:     True  (false = variable names NOT yet checked against the module)
# Sources:      {"ccc": ["CCC.Core (imported)"], "ccc_catalog_ref": "https://github.com/finos/common-cloud-controls/blob/main/catalogs/compute/virtual-machines/controls.yaml", "fedramp": []}
#
# See virtual-machine.provenance.json for the authoritative, machine-readable audit trail.

# Controls: CCC.Core.CN05  [coverage: partial]
# Limitation: Applies to Linux SSH; Windows admin access is governed
# differently. Key distribution is an operational concern.
account_credentials = {
  password_authentication_disabled = true
}

# Controls: CCC.Core.CN02  [coverage: partial]
# Limitation: Requires the EncryptionAtHost feature registered on the
# subscription and a supported VM size.
# Limitation: Uses platform-managed keys unless combined with a disk
# encryption set (see vm.encryption.os-disk-cmk).
encryption_at_host_enabled = true

# Controls: CCC.Core.CN03, CCC.Core.CN05  [coverage: supporting]
# Limitation: Managed identity is the auth principal, not MFA; CN03 (MFA for
# human access) is enforced via Entra Conditional Access / JIT, not this
# module.
managed_identities = {
  system_assigned = true
}

# Controls: CCC.Core.CN05  [coverage: supporting]
# Limitation: Requires a Gen2 image and a Trusted Launch-capable VM size;
# forces VM recreation if changed.
secure_boot_enabled = true

# Controls: CCC.Core.CN05  [coverage: supporting]
# Limitation: Requires a Gen2 image and Trusted Launch-capable size; forces
# VM recreation if changed.
# Limitation: vTPM enables measured boot/attestation but attestation itself
# is configured separately.
vtpm_enabled = true

# Controls: CCC.Core.CN04  [coverage: supporting]
# Limitation: Boot diagnostics is platform/serial telemetry only; full
# access/change auditing also needs diagnostic_settings + guest-level logging
# (Azure Monitor Agent).
boot_diagnostics = true
