# CONTROL-INFORMED CANDIDATE configuration, not a compliance attestation.
# Covers only technical settings expressible as AVM module inputs. Does NOT
# establish FedRAMP / CCC / NIST compliance. Mapped controls may be only
# partially satisfied; unmapped and process/evidence controls are out of scope.
# Human review and deployment-context validation are required before use.
#
# Generated by avm-config-generator v0.1.0
# AVM module:   Azure/avm-res-keyvault-vault/azurerm
# Module ver:   0.10.2  (provider azurerm >= 3.117, < 5.0)
# Verified:     True
# Sources:      {"ccc": ["CCC.KeyMgmt", "CCC.Core (imported)"], "ccc_catalog_ref": "https://github.com/finos/common-cloud-controls/blob/main/catalogs/crypto/key/controls.yaml", "ccc_retrieved": "2026-06-09", "fedramp": []}

variable "location" {
  description = "Azure region where the key vault should be deployed."
  type        = string
}

variable "name" {
  description = "Key vault name (3-24 chars; alphanumerics and hyphens, must start with a letter)."
  type        = string

  validation {
    condition     = can(regex("^[a-zA-Z][a-zA-Z0-9-]{1,22}[a-zA-Z0-9]$", var.name))
    error_message = "The name must be 3-24 characters, start with a letter, end with a letter or digit, and contain only letters, digits and hyphens."
  }
}

variable "resource_group_name" {
  description = "Name of the resource group in which to create the key vault."
  type        = string
}

variable "tenant_id" {
  description = "Entra ID tenant ID used for authenticating requests to the key vault."
  type        = string
}

variable "enabled_for_deployment" {
  description = <<-EOT
    Controls: CCC.KeyMgmt.CN02 [coverage: partial]
    Allow Azure Virtual Machines to retrieve certificates stored as secrets.
    Limitation: Matches the module default (false); emitted to make the least-privilege posture explicit. Set to true only when a workload genuinely needs it.
  EOT
  type        = bool
  default     = false
}

variable "enabled_for_disk_encryption" {
  description = <<-EOT
    Controls: CCC.KeyMgmt.CN02 [coverage: partial]
    Allow Azure Disk Encryption to retrieve secrets and unwrap keys.
    Limitation: Matches the module default (false); emitted to make the least-privilege posture explicit. Set to true only when a workload genuinely needs it.
  EOT
  type        = bool
  default     = false
}

variable "enabled_for_template_deployment" {
  description = <<-EOT
    Controls: CCC.KeyMgmt.CN02 [coverage: partial]
    Allow Azure Resource Manager to retrieve secrets during template deployment.
    Limitation: Matches the module default (false); emitted to make the least-privilege posture explicit. Set to true only when a workload genuinely needs it.
  EOT
  type        = bool
  default     = false
}

variable "legacy_access_policies_enabled" {
  description = <<-EOT
    Controls: CCC.KeyMgmt.CN02 [coverage: partial]
    Use legacy vault access policies instead of Azure RBAC. Keep false to use RBAC.
    Limitation: RBAC is the module default; this makes it explicit. The actual scoping of Decrypt to authorised principals is done via var.role_assignments (deployment-specific).
    Limitation: Does not itself assign or restrict any role.
  EOT
  type        = bool
  default     = false
}

variable "purge_protection_enabled" {
  description = <<-EOT
    Controls: CCC.KeyMgmt.CN01 [coverage: supporting]
    Prevent permanent deletion of the vault and its objects during the soft-delete window.
    Limitation: Preventive control for TH01; it does NOT satisfy CN01's actual requirement (near-real-time ALERT on key-version disable/delete) - that is covered separately.
    Limitation: Once enabled, purge protection cannot be disabled (module default is already true).
  EOT
  type        = bool
  default     = true
}

variable "soft_delete_retention_days" {
  description = <<-EOT
    Controls: CCC.KeyMgmt.CN01 [coverage: supporting]
    Number of days deleted vault objects are recoverable (7-90).
    Limitation: Recovery window only; does not satisfy CN01's alerting requirement.
  EOT
  type        = number
  default     = 90
}

variable "sku_name" {
  description = <<-EOT
    Controls: CCC.KeyMgmt.CN04 [coverage: partial]
    Key vault SKU (standard or premium). 'premium' enables HSM-backed keys.
    Limitation: SKU enables HSM-backed keys but does NOT itself enforce approved algorithms or attestation on import - that is an approval workflow.
  EOT
  type        = string
  default     = "premium"
}

variable "network_acls" {
  description = <<-EOT
    Controls: CCC.Core.CN05 [coverage: partial]
    Network ACLs for the key vault.
    Limitation: Allowed IP ranges (ip_rules) / subnet IDs (virtual_network_subnet_ids) are deployment-specific and intentionally left to the operator.
    Limitation: bypass=AzureServices is pragmatic; tighten to None for the strictest posture. bypass is a string (AzureServices|None), not a list.
  EOT
  type = object({
    bypass                     = optional(string, "None")
    default_action             = optional(string, "Deny")
    ip_rules                   = optional(list(string), [])
    virtual_network_subnet_ids = optional(list(string), [])
  })
  default = {
    default_action = "Deny"
    bypass         = "AzureServices"
  }
}

variable "public_network_access_enabled" {
  description = <<-EOT
    Controls: CCC.Core.CN05 [coverage: partial]
    Whether public network access is enabled for the vault.
    Limitation: Does NOT create private endpoints/DNS - configure var.private_endpoints on the AVM module for the vault to remain reachable.
  EOT
  type        = bool
  default     = false
}

variable "private_endpoints" {
  description = <<-EOT
    Controls: CCC.Core.CN05 [coverage: partial]
    Map of private endpoints to create (passed through to the AVM module). Each
    entry typically specifies subnet_resource_id and private_dns_zone_resource_ids.
  EOT
  type        = any
  default     = {}
}
